name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Build application
        run: docker build -t movements-middleend .

  docker-push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/movements-middleend:latest .

      - name: Tag Docker image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/movements-middleend:latest ${{ secrets.DOCKER_USERNAME }}/movements-middleend:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/movements-middleend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/movements-middleend:latest
